### ISSUE TITLE
Multiple or nested endpoints?

### ISSUE THREAD

**Issue by Kcko** [joesaunderson/sportmonks-soccer#13]
How can i set nested endpoints?

**Comment by joesaunderson** [comment]
What do you mean by nested endpoints?

**Comment by Kcko** [comment]
Hi,

eg:
`&include=fixtures.referee,fixtures.localTeam.coach,fixtures.visitorTeam.coach`

**Comment by Kcko** [comment]
And further:  where can I use additional parameters? 

for example:
->setLeagues(a,b,c) // generate url  &league=1,2,3

Where  and how can I use it? What makes this part of url? 

I work with SM over 2 years and can´t find something about this "option".

**Comment by joesaunderson** [comment]
For this Api Request:

https://www.sportmonks.com/docs/football/2.0/fixtures/a/get-by-date/11

There is a leagues parameter (not an include) which supports a comma separated list of league id's

**Comment by Kcko** [comment]
@joesaunderson Thx for link, i don't use this view, I didn't know it
