### ISSUE TITLE
Not working method (Stage -> getBySeasonId)

### ISSUE THREAD

**Issue by wpdomoneto** [joesaunderson/sportmonks-soccer#18]
sportmonks-soccer\src\Endpoint\Stage.php

**Current version:**    
public function getBySeasonId(int $seasonId)
    {
        $url = "stages/{$seasonId}";
        return $this->call($url);
    }

**Need version:**
    public function getBySeasonId(int $seasonId)
    {
        $url = "stages/season/{$seasonId}";
        return $this->call($url);
    }

Fix it please. Thank you.

**Comment by joesaunderson** [comment]
Hi there, feel free to raise this as a PR and get it in the next release.

**Comment by joesaunderson** [comment]
Fixed in https://github.com/joesaunderson/sportmonks-soccer/pull/20

**Comment by joesaunderson** [comment]
Released as https://github.com/joesaunderson/sportmonks-soccer/releases/tag/v0.3.2
