### ISSUE TITLE
Incorrect key in \Sportmonks\Soccer\SoccerClient::setIncludes breaks included data response.

### ISSUE THREAD

**Issue by emarketa** [joesaunderson/sportmonks-soccer#2]
I was not getting back include data on my test and after some debugging I found that using the plural was meaning the resulting URL was not correct; it should be `include=item,item,item` not `includes=item,item,item`.

See: https://github.com/joesaunderson/sportmonks-soccer/blob/bd2568eafc92fec8980aeac5c96413973327b4ec/src/SoccerClient.php#L95

**Comment by joesaunderson** [comment]
@emarketa - released in v0.2.2. Thanks for contributing :)
