### ISSUE TITLE
var_dump in the code

### ISSUE THREAD

**Issue by LittleSecrets** [joesaunderson/sportmonks-soccer#24]
![image](https://user-images.githubusercontent.com/2226710/99526661-3a095e80-29a4-11eb-8ebb-8e6a61e8cab4.png)

https://github.com/joesaunderson/sportmonks-soccer/blob/master/src/Endpoint/Fixture.php

str 49

**Comment by joesaunderson** [comment]
Closed in https://github.com/joesaunderson/sportmonks-soccer/pull/33
