### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ronnievisser** [joesaunderson/sportmonks-soccer#26]
Hi,

The sportmonks support team is trying to contact you but it seems the mails are ending up in spam or something. Can you reach out via a different email? We can then discuss how to proceed. 

Please remove this issue when you have read it!

Thanks

**Comment by joesaunderson** [comment]
> Hi,
> 
> The sportmonks support team is trying to contact you but it seems the mails are ending up in spam or something. Can you reach out via a different email? We can then discuss how to proceed. 
> 
> Please remove this issue when you have read it!
> 
> Thanks

Hi there, for some reason I have only just received this... please reach out on joesaunderson [at] me [dot] com
